### PR TITLE
Changing check intervals: 

### PR DESCRIPTION
**Pull request by jacentemu**
Previous intervals (delay between checks) was everywhere 60 sec. It is too often for values that doesn't change often (max values) or are almost constant. 

- from 60s to 3600s for config parameters
- from 60s to 600s for _max values.

Also updated version of Zabbix in header of template.

### CODE REVIEW

**Comment by mprenditore** [comment]
Thank you for your pull request.
The new values can reduce a little bit the number of the metrics to get per minute, but in case there is a change in one of this values, a graphs discrepancy can occur before the next value is retrieved. Am I wrong?

I know that the amount of checks that this template does it's huge, and because of that I've a new implementation in the branch `dependant_items` that will drastically reduce the amount of stress on the agent.
The new version uses the dependant items of zabbix, so the calls will be reduced only to one per each discovered object, and Zabbix will take care of populating other items.

If you'll try it, please let me know if you find any bug. I'm using on my systems since 2 weeks and the amount of metrics retrieved dropped from ~3800 to ~60. with a huge discount on the system resources.

**Comment by jacentemu** [comment]
I'm using Zabbix 3.0, but `dependant_items` are available since 3.4, so I cannot check this until upgrade to zabbix 4.0 (released few days ago). But I read about this and it sounds great!

The problem is not (not only) stressing agent (this is repaired by creating of cache file), but also fulfilling zabbix's database. I think, that HaProxy's config is not changed often, so one-hour graphs discrepancy seems to be unimportant, but changing intervals 60->3600 gives 60 times less values in database.

Next lines are about this Template at all, not only about this Pull Request.
- From my point of view, this Template has too many metrics enabled (in my setup, discovery generated about 800 items, about 300 active by default), which in without any default Triggers and good graphs are almost useless (for me). For example: I don't see reason for storing in Zabbix values like `Max session rate`, `Max sessions`. This values will remain constant until the size increases or the haproxy will be restarted. So changing interval to 10 minutes was compromise (maybe someone need this information).
- Other problem is that storing some values `As is` is useless too; many Items (more precisely: item prototypes) should have `Store value: Delta (speed per second)` and `Type of information: Numeris (float)`, as it is done for example in `Bytes in` and `Bytes out` items.
- Checking one time per minute `Current number of session` or `Session rate` doesn't have sense (there can be 59 second of high traffic and 1 second of silence). In my opinion this should be disabled or removed by default, and described in Readme or in bash scripts how to recreate it.

In my current config (not commited yet) I've removed or disabled most of items, and I've made changes on this (smaller) number of items and graphs (probably I should change my project name to "zabbix-haproxy-little-checks") After checking your work I'll try to make some Pull Requests, with propositon Triggers or Graphs.
Example of my change, not to storing requests number, but store changes (delta). After restarting HaProxy, Delta will be 0 (not a negative number).
```
Name: [{#FRONTEND_NAME}] calculated requests per sec
Key: haproxy.stats[{$HAPROXY_SOCK},{#FRONTEND_NAME},FRONTEND,req_tot]
Type of information: Numeric (float)
Units: req/s
Update interval (in sec):60
Store value: Delta (speed per second)
Description: number of HTTP requests received divided per number of second since last check, return average req/sec.
```

**Comment by mprenditore** [comment]
I get your point. I also find strange which are the default checks that are enabled, and most of them I neither enable, but this is meant to be the most general possible so I would never remove one items from it, at most I'll disable it by default, and I'd let people to decide what to enable by them self.
For example I didn't change the default enabled items in the template of the repo, but I kept the ones chosen by the original creator and made my changes only on my local installation.

If you make those changes regarding the `types` and the `post_processing` I'll be glad to have a look into it and merge them... If you would also like to create a new template with the values you think could be a  good starting point for a basic implementation, I've created a template folder in my `dependant_items` branch, and I've added a `README.md` where we can list the templates with a quick description to let the final user decide which one to use. If you want to add instead triggers, you can add them in all the templates and just disable them if the items are already disabled by defaults :).

By the way, thanks for the suggestion regarding the version of Zabbix for the dependent items, I've changed the template name to show that is for v3.4 ;)

**Comment by jacentemu** [comment]
You shouldn't accept this pull request or you should edit/leave zabbix versions in first line - should be still 2.0 (beacuse this is really export from zabbix 2.0, export from 3.0 should contain more tags and parameters).

**Comment by mprenditore** [comment]
Indeed, actually the templates v2 and v3 are almost identical except that the v3 have also the filters.

**Comment by jacentemu** [comment]
1. Currently I'm not able to check your work with `dependant_items` because of zabbix 3.0 version, and cannot make small changes on `haproxy_zbx_v3_template.xml` file, because this require from me manual writing in this file to remove all 2.0/3.0 differences. This file needs to be imported and exported using Zabbix 3.0, I can to it, but  `dependant_items` isn't correct branch for this. Maybe I should do this after you merge branch `dependant_items` to master? In next month I'll have zabbix 4.0, so I do not insist on changing this file.
2. Does your updated shell scripts work still without dependency items functions?
3. Do you know, why HaProxy socket is discoverd and send in every item name, if this socket is also defined in `haproxy_zbx.conf`?

**Comment by mprenditore** [comment]
1. If you can import and export the v3 template so we have all the xml tags needed and do a pull request to master I'll manually fix the `dependant_items` branch.
2. The modified script is backward compatible, I've just added a new custom function to get the full JSON for the dependent items.
3. It's useless since I've implemented the conf file, but I forgot to remove it... Is one of the things to do before to merge `dependant_items` to `master` ;)

**Comment by jacentemu** [comment]
Changes from point 1 (and point 3, only for file `haproxy_zbx_v3_template.xml`) are made by me in three commits in branch `master` 25449355c51f0cdc61691d8dc58cfc2cb5995d91 You can merge it where you want.
Point 2: I see that latest scripts from branch `dependant_items` works fine in my infrastructure with template `haproxy_zbx_v3_template.xml` from my branch 'master', nice. 

I think, that after successfully changes in your `haproxy_zbx_v3.4_template.xml` (removing sockets and maybe item `request total` to `calculated requests per second`), scripts can be cleared, there are many unused lines and there will be more unused lines.

In next days I'll have less time for that project. You can close this `Pull request` or leave it for this days as a chat :)

**Comment by mprenditore** [comment]
Thank you for your contributions. I'll take care of it as soon as possible ;)
I'll try to merge everything to master by the end of the week, I'm quite busy too :)

**Comment by mprenditore** [comment]
I've found some time to sort it out.
All merged to master.
If you can please test it will be awesome :)

Added also the cache expiration to seconds instead of minutes for a better control. ;)

**Comment by jacentemu** [comment]
I'm checking new scripts (after removing `HAPROXY_SOCS` from template), most time it works correct, but in Zabbix Server logs I see many times per day (for many different metrics):
```
[time] item "myhost:haproxy.stats[stats,BACKEND,bin]" became not supported: Received value [grep: /tmp/haproxy_stat.cache: No such file or directory9999999999] is not suitable for value type [Numeric (float)]
[time] item "myhost:haproxy.stats[beta,BACKEND,bout]" became not supported: Received value [grep: /tmp/haproxy_stat.cache: No such file or directory9999999999] is not suitable for value type [Numeric (float)]

[time+1min] item "active FIRE:haproxy.stats[stats,BACKEND,bin]" became supported
[time+1min] item "active FIRE:haproxy.stats[beta,BACKEND,bout]" became supported
```
parts of debug logs near time when this happens:
```
DEBUG: stat file expired/empty/not_found, querying haproxy to refresh it
(..)
DEBUG: ERROR: stats cache file exists, but it's empty -> destroying it!
DEBUG: cache_type => stat
DEBUG: using default get() method
DEBUG: _STAT    => 5:scur:9999999999  #this is other check than from zabbix logs
DEBUG: _INDEX   => 5
DEBUG: _DEFAULT => 9999999999
DEBUG: cache_type => stat
DEBUG: ERROR: bad beta/BACKEND
DEBUG: stat file expired/empty/not_found, querying haproxy to refresh it
DEBUG: return value (default) = 9999999999
DEBUG: using default get() method
DEBUG: stat file found, results have just been updated by another process...
DEBUG: using default get() method

```
1. It looks like error during updating of cache file, perhaps created when multiple check are created in the same time, but I'm not sure still (with about 130 active items DEBUG file grows fast). Or maybe it is just not silencing bash errors (returned value is `bash_error99999999`).
3. In DEBUG mode, in logs some date/timestamp would be very usefull. Also usefull would be information about what stats this entry is: sometimes logs from one check process are interlaced with the logs of another process, like `DEBUG: /BACKEND/stats: message`.
4. In DEBUG mode, logs says `DEBUG: CACHE_STATS_EXPIRATION => 60 minutes`, this message should be `seconds` ;)

**Comment by jacentemu** [comment]
It looks like `lock` mechanism doesn't work correct in every situation.  I've added `-s` option (silencing errors about `File not found`) to `grep` near line 236  in `get_resources(){` function https://github.com/mprenditore/zabbix-haproxy/blob/5f248fe3fa5ae0648814d0f0186e6a6c424dcd80/haproxy_stats.sh#L236
```
    if [ -z $2 ]; then
        local _res="$("${FLOCK_BIN}" --shared --wait "${FLOCK_WAIT}" "${CACHE_STATS_FILEPATH}${FLOCK_SUFFIX}" grep -s "$1" "${CACHE_STATS_FILEPATH}")"
    else
        local _res="$("${FLOCK_BIN}" --shared --wait "${FLOCK_WAIT}" "${CACHE_STATS_FILEPATH}${FLOCK_SUFFIX}" grep -s "$1" "${CACHE_STATS_FILEPATH}" | tee $2)"
```
and errors in `zabbix_server.log` changes:
```
  4697:20181018:113822.235 item "myhost:haproxy.stats[back_beta,beta1,bin]" became not supported: Received value [ERROR: bad back_beta/beta19999999999] is not suitable for value type [Numeric (float)]
  4693:20181018:114421.780 item "myhost:haproxy.stats[back_beta,beta1,bin]" became supported
```
So this hotfix his only changes error, but script still return in that case `Error+defaultvalue`. Im not sure what should return: 
-error (item became unsupported), 
-default value (zabbix statistics will be totally incorrect)
-or empty response (how zabbix will interpret this?

To reproduce error, you should change `${CACHE_STATS_FILEPATH}` to non-existing file in line 236:
```
local _res="$("${FLOCK_BIN}" --shared --wait "${FLOCK_WAIT}" "${CACHE_STATS_FILEPATH}${FLOCK_SUFFIX}" grep -s "$1" "/tmp/file-not-exists.txt")"
```
And then querry script for example `./haproxy_stats.sh your_frontend FRONTEND req_tot`

This script is too complicated for me, I will not look at this more until upgrading my Zabbix to 4.0, I think that with `dependant items` this problem doesn't exists, because of much less queries to HaProxy agent. And I saw, that this problem occurs also in previous versions of this script (before adding `dependant item` functions).

**Comment by mprenditore** [comment]
### Cache file problem
I added this kind of problems on my installation too, I had more than 4000 items to monitor and that resulted on various of those errors. The FLOCK should avoid that but I don't know why it happens. From my research I went out with a theory:
- every item collecting takes around 33ms
- 33ms * 4000 = around 130secs to elaborate  all items.
- default number of zabbix agent thread started is 3 that means more than 40secs to elaborate all of them
- the default FLOCK_WAIT is 15secs so some times the lock is expiring before to collect it

In your case you should check how long it takes the execution of a single check running the following command from the Zabbix Server:
`time zabbix_get -s myhost -k haproxy.stats\[back_beta,beta1,bin\]`

multiply the execution time by the number of items you've enabled on `myhost` and divide it by 3 (unless you modified the zabbix agent conf value "StartAgents", in which case you have to use your own value) and you should get the minimum amount in seconds for the FLOCK_WAIT.

### Wrong output
Regarding instead the strange output you  get when the cache file is not read, it seems the `set -o pipefail` is not working letting the script to keep executing instead of exit immediately with the error code. I never experienced such behavior, can you try my new branch `fixing_exits`? I'll make few changes there so you can test different commits to see which one solve your problem.

### Debug
BTW I've fixed the CACHE_EXPIRATION debug message to show seconds and added a timestamp, you find them on `master` and on `fixing_exits` ;)

**Comment by jacentemu** [comment]
**Cache file problem**
Time of `zabbix_get` execution is in my setup about `real	0m0.302s`, in my config this is `0,302*132/3=13,3 sec`, so less than 15 seconds.

After increasing number of zabbix agents to `StartAgents=6` the problem still occurs - first time, one hour after increasing agents number and changing script to current `master`, version 9c231f8283065d42da6fce1eef26c532e3e76351 
```
4693:20181019:125621.428 item "myhost:haproxy.stats[beta,FRONTEND,bout]" became not supported: Received value [grep: /tmp/haproxy_stat.cache: No such file or directory9999999999] is not suitable for value type [Numeric (float)] 
```

**Wrong output**
Output as above - bash error visible, but no more information like `ERROR: bad back_beta/BACKEND`.

**Debug**
TImestamp works great :) Usefull could be adding to debug log information about process instance, perhaps PID, or something like `[timestamp] DEBUG: pxname,svname,stat: message`. PID is shorter, so in my opinion better.

**Comment by mprenditore** [comment]
### Cache file problem
Ok, reading the documentation the `StartAgents` seems to be involved only of passive items, for active checks I don't find information about how many threads are taking care of the checks so, it make sense that increasing the number of threads doesn't solve the issue.
If we assume that just one thread is used in case of active checks, with your parameter you should require a `FLOCK_WAIT` of around 45 secs. Please try to increase it to 60 sec.

###  wrong output
Please check the latest commit in `fixing_exits`

### Debug
I can add the PID, let's try to fix the error code and i'll add it later on

**Comment by jacentemu** [comment]
**Cache file problem**
StartAgents is about passive check, and this is exactly what Zabbix Agent do in this Template ([link](https://www.zabbix.com/documentation/3.0/manual/appendix/items/activepassive)). Active checks are not used here.
But true is that increasing Agent process doesn't change situation. I'm loking on server load and process list (currently using htop) and I see that Zabbix Agent processes are not busy, there are waiting for most time (`TIME+` column in htop shows time of CPU usage - it increase only when process work).

I've tested different configurations:
`CACHE_STATS_EXPIRATION=60 + FLOCK_WAIT=15` default
`CACHE_STATS_EXPIRATION=4  + FLOCK_WAIT=1`
`CACHE_STATS_EXPIRATION=4 + FLOCK_WAIT=10`
`CACHE_STATS_EXPIRATION=10 + FLOCK_WAIT=1`
`CACHE_STATS_EXPIRATION=10 + FLOCK_WAIT=15`
And no ERROR in debug log or in `zabbix_server.log`..

**Comment by mprenditore** [comment]
So you don't have any ERROR anymore?
Having a so low FLOCK_WAIT is quite dangerously because you can risk to lose metrics. You have few metrics so it shouldn't be a problem, bu that can cause issues on bigger installations.

Which commit are you using right now?

**Comment by jacentemu** [comment]
Unfortunately, I have 12 errors in the last 3 hours, using 04ea82f8429cfbb8d164616a79677dc3505ceb94 script. Errors like this:
```
myhost:haproxy.stats[back_betax,betax1,bout]" became not supported: Received value [grep: /tmp/haproxy_stat.cache: No such file or directory9999999999] is not suitable for value type [Numeric (float)]
myhost:haproxy.stats[beta,BACKEND,stot]" became not supported: Received value [grep: /tmp/haproxy_stat.cache: No such file or directory] is not suitable for value type [Numeric (float)]
myhost:haproxy.stats[back_betax,betax1,qcur]" became not supported: Received value [grep: /tmp/haproxy_stat.cache: No such file or directory9999999999] is not suitable for value type [Numeric (unsigned)]
```
I wrote previous messages after few minutes of testing each combination, only to check, if it is wrong time of FLOCK_WAIT.

Now I'll update to the latest 142ec5882a812781b794e912a0c5ccebb65690f2 and I'll leave it for weekend or more.

**Comment by mprenditore** [comment]
Please, try this setting:
`FLOCK_WAIT=60`
`CACHE_STATS_EXPIRATION=60`
and leave it for at least 1 hour, more is better because the error doesn't fire immediately.
If it doesn't work try 120 for both.

If you keep on receiving errors try to change the items type to `Zabbix Agent (active)` and check if the errors are less or more.

**Comment by jacentemu** [comment]
Ok, I set `60,60`.

**Comment by jacentemu** [comment]
1. Does this error occur in your Zabbix 3.4 with `dependant items`?  In my Zabbix 3.0, both with 30/30 and 60/60 the errors still occurs:
`item (..) became not supported: Received value [grep: /tmp/haproxy_stat.cache: No such file or directoryERROR: bad asdf/asdf]  is not suitable for value type [Numeric (float)]`

BTW, I left the values set to:
```
CACHE_STATS_EXPIRATION=30  # in seconds
FLOCK_WAIT=30 # maximum number of seconds that "flock" waits for acquiring a lock
```
with 60/60 every ~38 minutes the readings of items were zero - it means that Zabbix get two times response from the same cached file (items have 60sec intervals). On my server traffic was constant, but graph show "0" value once every 38-40 minutes.


2. I made pull request with request/minute in frontend. Graph from this change is what I use mostly.
3. Although there are errors, but statistic works, so until upgrading my server to Zabbix 4.0 I will not work with this.

**Pull request merged**
